### ISSUE TITLE
cannot login with mac built in apache

### ISSUE THREAD

**Issue by phaizt** [HuasoFoundries/phpPgAdmin6#215]
Hello, I cannot login if i use mac built in apache and php. but it will fine if i use AMPPS webserver. is there any configuration that you missed in documentation?

**Comment by phaizt** [comment]
i just reconfigure my local web server with brew. and it working fine.

**Comment by amenadiel** [comment]
I forgot to say I was trying to reproduce the problem. Glad it worked out
