### ISSUE TITLE
PHP 7.4 Breaks UI

### ISSUE THREAD

**Issue by klaxian** [HuasoFoundries/phpPgAdmin6#234]
Upgrading to PHP 7.4 breaks the UI. Frames are in the wrong place and it is unusable. There is probably a new warning or error preventing everything from being rendered correctly.

**Comment by ffflabs** [comment]
It seems related to an open issue in php console
https://github.com/barbushin/php-console/issues/165

I'll check if it's easy to remove said dependency. However, composer complained a lot too, and I'm afraid other things might be broken on 7.4.

**Comment by ffflabs** [comment]
@klaxian I refactored quite a bit and released as v6.0.0-RC1.
(the important part was leaving PHP-Console aside for PHP_VERSION>=7.4)
