### ISSUE TITLE
Error when Browsing/Searching with PG 12

### ISSUE THREAD

**Issue by klaxian** [HuasoFoundries/phpPgAdmin6#245]
When browsing or performing a search on a table in a PostgreSQL 12 database, the following error is displayed. I suspect this is related to the [OID changes](https://www.postgresql.org/docs/12/release-12.html#id-1.11.6.6.4) in PG 12.

`SELECT relhasoids
FROM pg_catalog.pg_class
WHERE relname='products_attributes'
AND relnamespace = (
SELECT oid
FROM pg_catalog.pg_namespace
WHERE nspname='xxxxx')`
`ERROR: column "relhasoids" does not exist`

**Comment by ffflabs** [comment]
Got it, I'm uploading a new release (6.0.0-RC3) to override the method from PG12 onwards.

**Comment by klaxian** [comment]
Now I'm getting the following warnings when browsing/searching. I think these are related to PHP 7.4 because these would have been notices prior to PHP 7.4. Now they are warnings. Would you prefer a separate issue? debugmode is false.

`Warning: array_keys() expects parameter 1 to be array, null given in /var/www/phppgadmin-hf/src/controllers/DisplayController.php on line 139`
`Warning: Invalid argument supplied for foreach() in /var/www/phppgadmin-hf/src/database/ADOdbBase.php on line 140`
`Warning: sizeof(): Parameter must be an array or an object that implements Countable in /var/www/phppgadmin-hf/src/database/Postgres.php on line 841`

**Comment by klaxian** [comment]
Sorry, the warnings I listed in my last comment do affect PHP 7.2 also. I'm not sure if they were a result of this fix or my other ticket about broken pagination. I suspect the latter. Let me know if you want a new issue.

**Comment by klaxian** [comment]
I created issue #251 for the new problem.
