### ISSUE TITLE
Broken Sorting and Pagination for Search Results

### ISSUE THREAD

**Issue by klaxian** [HuasoFoundries/phpPgAdmin6#246]
Navigating to different search result pages or clicking a column heading to sort search results brings the user to a list of all tables instead of actually updating the visible results. This only seems to affect searches, not browsing all records. This is not a new issue; it has actually existed for years.

**Comment by ffflabs** [comment]
okay, can you paste some screenshots? I'm not sure if you mean queries or searches

**Comment by ffflabs** [comment]
Got it! and you're right, I kinda fixed it
