### ISSUE TITLE
No Indexes Found

### ISSUE THREAD

**Issue by klaxian** [HuasoFoundries/phpPgAdmin6#253]
After the latest update, indexes are no longer display in the "Indexes" tab when viewing tables. The UI always shows "No indexes found." even when indexes do exist. This affects PG 10 and 12, PHP 7.2 and 7.4.

**Comment by ffflabs** [comment]
I'm afraid I don't know what's going on there, but now it's working :D

**Comment by Kvark1205** [comment]
Absolutely same issue here. Using PG 12 and PHP 7.3

**Comment by ffflabs** [comment]
I'm uploading a new tag. I believe quite a few problem came from a fix I did to the pagination. Damnit

Please see release RC4

**Comment by klaxian** [comment]
Can you merge your changes into master? I see them in develop, but not master. Thanks.

**Comment by ffflabs** [comment]
Damn you're right... I had gitlab as master's upstream. Why do you need master? Are you using git instead of composer?

**Comment by klaxian** [comment]
Yes, I was using git. I think I cloned with git a long time ago to debug something and I just stuck with it. However, I just installed with composer (beta) and I'm still getting RC4. It looks like your tests failed. Can you replace `dump()` with `$this->dump()` in ActionUrlDecorator.php on line 37? Thanks.

**Comment by klaxian** [comment]
RC6 fixed the error with `dump()`. Commenting it out works just as well. Thanks!
