### ISSUE TITLE
Default NULLs when Editing

### ISSUE THREAD

**Issue by klaxian** [HuasoFoundries/phpPgAdmin6#254]
When editing a row with NULL values, the applicable NULL checkboxes should be checked by default. Currently, they are all always unchecked, which attempts to performs unintended updates when saving.

**Comment by ffflabs** [comment]
@klaxian  I'll work on these issues as soon as I catch a breath, which I believe will be on friday

**Comment by klaxian** [comment]
Thank you for all your hard work!

**Comment by ffflabs** [comment]
This one still puzzles me. I cannot reproduce it consistently for it happend in chrome but not in firefox.
