### ISSUE TITLE
Errors During Initial Composer Installation

### ISSUE THREAD

**Issue by klaxian** [HuasoFoundries/phpPgAdmin6#255]
When initially installing via composer, I get the following errors. I realize these are just due to missing directories, but perhaps they could be created automatically?
> php -r "chmod( __DIR__ . '/temp', 0777);"
> php -r "chmod( __DIR__ . '/temp/twigcache', 0777);"
> php -r "chmod( __DIR__ . '/temp/jms', 0777);"

Warning: chmod(): No such file or directory in Command line code on line 1

Call Stack:
    0.0000     394888   1. {main}() Command line code:0
    0.0000     394888   2. chmod() Command line code:1

> php -r "chmod( __DIR__ . '/temp/logs', 0777);"
> php -r "chmod( __DIR__ . '/temp', 0777);"
> php -r "chmod( __DIR__ . '/temp/twigcache', 0777);"
> php -r "chmod( __DIR__ . '/temp/jms', 0777);"

Warning: chmod(): No such file or directory in Command line code on line 1

Call Stack:
    0.0000     394888   1. {main}() Command line code:0
    0.0000     394888   2. chmod() Command line code:1

> php -r "chmod( __DIR__ . '/temp/logs', 0777);"

**Comment by klaxian** [comment]
I think the only missing directory is actually `/temp/jms`

**Comment by ffflabs** [comment]
You already figured it out, you should make a PR since you're the power user (by far)

**Comment by klaxian** [comment]
Ok I'll dig in a bit and get my hands dirty. I just didn't want to step on any toes. Also, you know more about the codebase and these frameworks. I'll make PRs in the future if I have time.

**Comment by ffflabs** [comment]
Remember this is a spin-off of the original phpPgAdmin which is coded in procedural programming. I rewrote most of it, but the underlying logic is still another's work. I'll leave composer bug untouched for now so you can chip in.

Version RC6 is on the way

**Comment by klaxian** [comment]
Yeah, I used the original phpPgAdmin for years, but I like your spin-off much better!
