### ISSUE TITLE
Query formatting is missing

### ISSUE THREAD

**Issue by Kvark1205** [HuasoFoundries/phpPgAdmin6#256]
After updating to RC4/5 there is query formatting missing. Query shows as simple text like simple html input tag: no lines, tabulation ain't working and syntax without highlight.

**Comment by ffflabs** [comment]
it's seems it's some kind of race condition, CodeMirror tries to create its container but something's missing. I tried several times until it happened. Let's see if I can fix it

**Comment by ffflabs** [comment]
Ok, so now I'm using another approach on which CodeMirror starts without enhancements nor plugins, but instead loads them dinamically when it has finished bootstrapping. Please try and let me know.

**Comment by Kvark1205** [comment]
Lines and tabulation are working now as before, but there is still highlight syntax missing. Anyway that's much better than was. Ty!
