### ISSUE TITLE
Return to Results after Insert

### ISSUE THREAD

**Issue by klaxian** [HuasoFoundries/phpPgAdmin6#266]
After inserting a record into a table from the "Browse" tab by clicking the "Insert" button at the bottom of the list, return to the results that were previously displayed. Currently, the user is taken to a list of all tables in the current schema after inserts, which is not helpful to the user.

**Comment by klaxian** [comment]
This is an enhancement request. If you want to give me permission to tag issues, I will categorize them for you.

**Comment by ffflabs** [comment]
I sent you an invite
