### ISSUE TITLE
Sizes Missing with PG 12

### ISSUE THREAD

**Issue by klaxian** [HuasoFoundries/phpPgAdmin6#268]
There are no values in the Size columns for tables or schemas. "N/A" is always shown instead. I think this only affects PG 12 (possible due to the OID change) since it is working normally on PG 10.

**Comment by klaxian** [comment]
This could be because my config file was out of date and missing a `$conf['display_sizes']` variable. I will test again with a new config once the latest bug is fixed, which prevents the app from loading at all.

**Comment by ffflabs** [comment]
Fixed in v6.0.0
