### ISSUE TITLE
Pagination Error with Popup Select Query

### ISSUE THREAD

**Issue by klaxian** [HuasoFoundries/phpPgAdmin6#269]
When manually executing a query from the SQL popup window that returns paginated results, clicking on any page number or previous/next causes an error. This only happens sometimes (but often). It might be that the executed query from the popup is not always transferred to the main frame.

**Comment by ffflabs** [comment]
At some point we tried to treat the behaviour of browsing a table's records with the outcome of a popup query, it seems the treatment of the pagination was missing in some workflows. It's fixed in release v6.1.0
