### ISSUE TITLE
Default Config Missing Version

### ISSUE THREAD

**Issue by klaxian** [HuasoFoundries/phpPgAdmin6#275]
The default config.inc.php-dist is missing a version variable so the following error is displayed to the user. I performed a fresh install with composer and found this issue. Also, the version displayed for a fresh composer install is "vv6.0.0-RC8-20-g1bc0ba72", but I was expecting RC9.

> Your config.inc.php is out of date. You will need to regenerate it from the new config.inc.php-dist.

**Comment by ffflabs** [comment]
Oops, I moved said parameter to the YAML config file. I restored it where it belongs
