### ISSUE TITLE
Lost the ability to run in a subdirectory

### ISSUE THREAD

**Issue by LordAro** [HuasoFoundries/phpPgAdmin6#28]
Liking what you're doing with phppgadmin, considering how dead upstream is

However, it appears that in your changes you've made it so that you can no longer use phppgadmin in a subdirectory, e.g. example.com/phppgadmin . This appears to be because of hardcoded / at the beginning of all filepaths.

Would be excellent if you could restore this ability :)

**Comment by amenadiel** [comment]
I could try. However, keeping static assets linked relatively to current url won't be trivial once you right click somewhere on the tree and display a section on its own as opposed to displaying it in a frameset.

**Comment by LordAro** [comment]
Yeah, that's about as far as I got when trying to fix it myself...

On 28 Mar 2017 00:32, "Felipe Figueroa" <notifications@github.com> wrote:

I could try. However, keeping static assets linked relatively to current
url won't be trivial once you right click somewhere on the tree and display
a section on its own as opposed to displaying it in a frameset.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/HuasoFoundries/phppgadmin/issues/28#issuecomment-289617033>,
or mute the thread

**Comment by jangrewe** [comment]
Yes, restoring this functionality would be crucial - thanks! =)

**Comment by amenadiel** [comment]
I'm working on  this

**Comment by amenadiel** [comment]
This should have been settled with the merge of #40 
I'll release this as Release beta 17

**Comment by jangrewe** [comment]
I'm running e012bbed440d46e9f569e6a78f82386f7356d130, but i still only get two panes with 404 =(

**Comment by jangrewe** [comment]
ah, nevermind! Fixing the Nginx config solved it. Thanks!

**Comment by amenadiel** [comment]
@jangrewe 
Yeah, nginx config is mandatory. Remember that you could be running, for example, wordpress on the domain root, and phpPgAdmin6 on a subfolder. Each of them have different rewrite rules.
