### ISSUE TITLE
Fork and Rebrand Into New Product

### ISSUE THREAD

**Issue by zschuessler** [HuasoFoundries/phpPgAdmin6#29]
The main phppgadmin repository appears long-abandoned:

https://github.com/phppgadmin/phppgadmin/pull/35

Would the maintainers of this fork be interested in rebranding into a new product?

**Comment by amenadiel** [comment]
You mean, unfork this repo and convert it into a project on its own, likely names phpPgAdmin6 ?

I could, tho there are several issues we'd need to clarify before proceeding

- I'm not sure the original author would be OK with that. It would become some kind of hostile fork. Although most of the logic has been refactored, it's still mostly a reorganization of version 5 into routes, views and controllers. This means it's still a lot of HIS code. (Perhaps it would be enough to start the README.md saying that this project started as a fork and evolved into a project on its own). 

- If this project grains traction, more issues will arise. At this point I don't have any collaborators on this project. I'd gladly accept any help offerings, of course. I'm somewhat tempted to contact people that have been submitting PRs to the original repo without any answer whatsoever. But that still feels like stealing people and fragmenting the community.

**Comment by amenadiel** [comment]
@zschuessler I contacted github support and they detached the fork. This is now an independent repo.
