### ISSUE TITLE
Wide range of code standards / code smell

### ISSUE THREAD

**Issue by richp10** [HuasoFoundries/phpPgAdmin6#32]
Congrats on the hard fork - the right thing to do..

I use the excellent PHP inspections plugin for phpstorm (https://plugins.jetbrains.com/plugin/7622-php-inspections-ea-extended-) which runs a large number of coding standards / code quality tests.  It is throwing up a large number of issues - many of which I think I can fix.  For example, PHPDoc definitions would be good throughout the project. 

Shall I just fix those I think would be useful and submit PR - or do you want an issue ticket for each?

**Comment by amenadiel** [comment]
Please, by all means do fix as much as you can.
Are you interested in becoming a stable collaborator of this project?

**Comment by richp10** [comment]
To be blunt I am unlikely to be a good enough coder to be a stable collaborator.  That said, I have found the phpstorm inspections to massively improve my own coding though and I think I can add some value by kicking some of the legacy code toward modern standards, adding phpdoc definitions and things like that.  Let me have a go at making some improvements and you can see whether you think these are worthwhile.

**Comment by amenadiel** [comment]
:-1:  I'm really needing a hand here. At least to keep an eye on new issues.

**Comment by richp10** [comment]
Done: https://github.com/HuasoFoundries/phpPgAdmin6/pull/39
