### ISSUE TITLE
Creating database fails, and tries on wrong server if logged into multiple

### ISSUE THREAD

**Issue by tingvold** [HuasoFoundries/phpPgAdmin6#334]
PostgreSQL 9.6.15
phpPgAdmin6 on latest master-branch (16b6650)
nginx/1.18.0
php7.3 (7.3.19-1~deb10u1)

Trying to create a database fails with the following error;
```
strsqlerror
ERROR: zero-length delimited identifier at or near """"

LINE 1: ...t1" WITH TEMPLATE="template1" ENCODING='UTF-8' TABLESPACE ""

^

SQL:
CREATE DATABASE "kek-test1" WITH TEMPLATE="template1" ENCODING='UTF-8' TABLESPACE ""
```

![image](https://user-images.githubusercontent.com/359918/92598660-63718400-f2a9-11ea-9488-8cb97a4abb24.png)

Additionally, if you are connected to multiple servers, it will attempt to create the database on the server you logged into first.

1. Log into server1
2. Log into server2
3. Try to create database on server2
4. The creation fails, but shows that it tried to create it on server1

![image](https://user-images.githubusercontent.com/359918/92598778-90be3200-f2a9-11ea-8565-a2255c448aa3.png)
![image](https://user-images.githubusercontent.com/359918/92598787-94ea4f80-f2a9-11ea-82dd-a2332b10c111.png)

**Comment by tingvold** [comment]
Video showing the issue (including issue #333 and #334): https://files.jocke.no/debug/phppgadmin6-issues_20200909.mov

**Comment by tingvold** [comment]
As a (moot) comparison, this works fine using phpPgAdmin v6.0.0-b28 on PostgreSQL 9.6.10.

**Comment by ffflabs** [comment]
I see... this one has the same origin https://github.com/HuasoFoundries/phpPgAdmin6/commit/2b72a6599564901461c9c537e641b58f9fe8cd62 
having the collation , encoding and namespace not set, it shouldn't be using those parameters, but it was comparing empty strings with nulls, therefore there wasn't strict equality .

I'm releasing the fix as v.6.1.2
