### ISSUE TITLE
Server-list does not refresh after a login

### ISSUE THREAD

**Issue by tingvold** [HuasoFoundries/phpPgAdmin6#335]
PostgreSQL 9.6.15
phpPgAdmin6 on latest master-branch (16b6650)
nginx/1.18.0
php7.3 (7.3.19-1~deb10u1)

When logging into new servers, the server-list/left window is not refreshed, showing that the server is still "offline"/not logged in. A manual refresh of the window (using the refresh-button) works.

**Comment by tingvold** [comment]
Video showing the issue (including issue #333 and #334): https://files.jocke.no/debug/phppgadmin6-issues_20200909.mov

**Comment by tingvold** [comment]
As a (moot) comparison, this works fine using phpPgAdmin v6.0.0-b28 on PostgreSQL 9.6.10.

**Comment by ffflabs** [comment]
Gotcha, it's solved in the latest release.  The instruction to refresh the server's tree was set in the view's body, but since it was inmediately redirected to the databases view it never quite executed. Now I'm using a flash message to take care of that on the next request.
