### ISSUE TITLE
Display Foreign Tables?

### ISSUE THREAD

**Issue by ffflabs** [HuasoFoundries/phpPgAdmin6#38]
When using extension `postgres_fdw` you can mount a table from another database on a table on your own database.

You can also mount a schema from another database into a schema of your own.

However, phppgadmin doesn't display these tables. Perhaps there should be an extra tab displaying foreign tables when extension `postgres_fdw` is present on the system?

**Comment by DavidWC** [comment]
Could this be opened again?  I use foreign tables occasionally, and it would be useful to see them with pgpPgAdmin.
