### ISSUE TITLE
POST/GET/DELETE methods

### ISSUE THREAD

**Issue by ffflabs** [HuasoFoundries/phpPgAdmin6#4]
We should use Slim to render the proper result for requests, specially because at this point the controller methods are exposed to all verbs.

This would allow proper isolation of destructive methods vs read_only methods.

**Comment by amenadiel** [comment]
The main difficulty of this chore lies in that the $_REQUEST superglobal is modified several times during the request lifecycle, using it as an ephemeral storage for variables. 

Slim framework allows to get parameters from the $_REQUEST object searching them in the $_GET params (`Request::getQueryParams()`) and $_POST params (`Request::getParsedBody()`). But doesn't allow to set a request variable unless you set it both as a Query Parameter and a Parsed Body Parameter, which might have side effects.

A possible workaround would be to have a container inside the app container that could store arbitrary variables and could copy the $_REQUEST contents at the beggining of the request lifecycle, replacing the $_REQUEST superglobal for the rest of the lifecycle using native container setters and getters.
