### ISSUE TITLE
Change string to single quote

### ISSUE THREAD

**Issue by ffflabs** [HuasoFoundries/phpPgAdmin6#46]
There are several html string in the controllers using double quotes.
Some of them begin or end with "\n". This newline character must use double quotes, so the solution would be to transform

```php
$html = "This is a sentence \n";
```
to

```php
$html = 'This is a sentence ' . "\n";
```

Eventually, this would help to get rid of unnecesary double quotes.

**Comment by amenadiel** [comment]
This would also be mitigated as we transform more text blocks into twig templates.
